portfolio/main/urls.py
from django.conf.urls import url

from main.views import (HomepageView, MeetAIView, ResumeView, ResearchView, DetectionView,
                        LatexBeamerThemeView, LatexBeamerKelloggView, LatexBeamerNorthWesternView)

urlpatterns = [
    url(r'^$', HomepageView.as_view(), name='homepage'),
    url(r'^meet-ai/$', MeetAIView.as_view(), name='meet_ai'),
    url(r'^resume/$', ResumeView.as_view(), name='resume'),
    url(r'^research/$', ResearchView.as_view(), name='research'),
    url(r'^latex-beamer-theme/$', LatexBeamerThemeView.as_view(), name='latex_beamer_theme'),
    url(r'^latex-beamer-presentation-kellogg/$', LatexBeamerKelloggView.as_view(), name='latex_beamer_kellogg'),
    url(r'^latex-beamer-presentation-northwestern/$', LatexBeamerNorthWesternView.as_view(), name='latex_beamer_northwestern'),
    url(r'^detection/$', DetectionView.as_view(), name='detection'),
]

portfolio/portfolio/urls.py
from django.conf.urls import *
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.views.generic.base import TemplateView


urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
]


urlpatterns += [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('main.urls', 'main'), namespace='main')),
]

if settings.DEBUG:
    urlpatterns += [
        # Testing 404 and 500 error pages
        url(r'^404/$', TemplateView.as_view(template_name='404.html'), name='404'),
        url(r'^500/$', TemplateView.as_view(template_name='500.html'), name='500'),
    ]

    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]

portfolio/core/models.py
from django.db import models

# Create your models here.

portfolio/main/models.py
from django.db import models


class Skill(models.Model):
	title = models.TextField()

	class Meta:
		verbose_name = 'Skill'
		verbose_name_plural = "Skills"


class AIProject(models.Model):
	title = models.CharField(max_length=255)
	slug = models.SlugField()

	class Meta:
		verbose_name = 'Ai Project'
		verbose_name_plural = 'AI Projects'


class Contact(models.Model):
	name = models.CharField(max_length=255)
	email = models.EmailField()
	number = models.CharField(max_length=14)
	message = models.TextField()

	class Meta:
		verbose_name = 'Contact'
		verbose_name_plural = "Contacts"


class Research(models.Model):
	title = models.CharField(max_length=255)
	author = models.CharField(max_length=50)
	slug = models.SlugField()
	description = models.TextField()

	class Meta:
		verbose_name = 'Research'
		verbose_name_plural = 'Researches'

portfolio/main/forms.py
from django import forms

from .models import Contact


class ContactForm(forms.ModelForm):
	class Meta:
		model = Contact
		fields = '__all__'

portfolio/core/views.py
# Create your views here.

portfolio/main/views.py
# Create your views here.
from django.http import JsonResponse
from django.views.generic import TemplateView, CreateView
from django.contrib import messages
from .models import Skill, AIProject, Research
from .forms import ContactForm

class HomepageView(TemplateView):
	template_name = 'home.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['skills'] = Skill.objects.all()
		return context


class MeetAIView(TemplateView):
	template_name = 'meet_ai.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['ai_projects'] = AIProject.objects.all()
		return context


class ResumeView(CreateView):
	template_name = 'resume.html'
	form_class = ContactForm

	def form_valid(self, form):
		"""If the form is valid, save the associated model."""
		self.object = form.save()
		messages.success(self.request, "Thanks for submitting contact us form, I'll get back to you")
		return super().form_valid(form)

	def get_success_url(self):
		return self.request.path


class ResearchView(TemplateView):
	template_name = 'research.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['researches'] = Research.objects.all()
		return context


class LatexBeamerThemeView(TemplateView):
	template_name = 'latex_beamer.html'


class LatexBeamerKelloggView(TemplateView):
	template_name = 'latex_beamer_kellogg.html'


class LatexBeamerNorthWesternView(TemplateView):
	template_name = 'latex_beamer_northwestern.html'


class DetectionView(TemplateView):
	template_name = 'detection.html'

	def post(self, request, *args, **kwargs):
		def post(self, request, *args, **kwargs):
			image = request.FILES.get('image')
			return JsonResponse({'image':'',},status=200)

portfolio/templates/base.html
{% load i18n staticfiles compress sekizai_tags i18n %}

<!DOCTYPE html>
<html lang="{{ request.LANGUAGE_CODE }}">
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block page_title %} {% if page_title %}{{ page_title }}{% endif %}
        {% trans 'Rohit Patel' %} {% endblock %}</title>
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <meta name="author" content="{% block meta_author %}{% endblock %}">
    <meta name="viewport" content="width=device-width" initial-scale="1">

    <link rel="manifest" href="{% static 'site.webmanifest' %}">
    <link rel="apple-touch-icon" href="{% static 'imag/icon.png' %}">
    <!-- Place favicon.ico in the root directory -->
    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <!--<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" /> -->
    {% block meta %}{% endblock %}
    <!-- CSS -->
    {# use the CDN to get bootstrap css. can not be inside compress css block #}
    {% block cdn_css %}
        <link href="https://fonts.googleapis.com/css?family=Muli|Raleway:300,300i,400,400i,500,600,700"
              rel="stylesheet">
    {% endblock %}

    {% compress css %}
        <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/cast.css' %}">
        {% block css %}
        {% endblock %}
    {% endcompress %}
    {% render_block "css" %}
    {% compress js %}{% endcompress %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
          <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.js"></script>
          <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js"></script>
        <![endif]-->
</head>
<body data-target=".navbar-collapse" data-offset="500" class="{% block body_class %}{% endblock %}"
        {% block body_attributes %}{% endblock %} >
{#        {% cms_toolbar %}#}
{#        {% show_menu 0 100 100 100 "menu.html" %}#}
{% include 'menu.html' %}
<!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
     chromium.org/developers/how-tos/chrome-frame-getting-started -->
<!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
          <![endif]-->

{% block content %}{% endblock %}

<!-- JavaScript -->
<!-- JavaScript at the bottom for fast page loading -->
<!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
{% block cdn_js %}
{% endblock cdn_js %}
<!-- scripts concatenated and minified via django-compressor -->
{% compress js %}
    <script src="{% static 'js/vendor/modernizr-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/smoothscroll.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <script>

        $(document).click(function (e) {
            if (!$(e.target).is('.panel-body')) {
                $('.collapse').collapse('hide');
            }
        });
    </script>
    {% block js %}
    {% endblock js %}
{% endcompress %}
    <script>
        window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
        ga('create', 'UA-XXXXX-Y', 'auto'); ga('send', 'pageview')
    </script>
    <script src="https://www.google-analytics.com/analytics.js" async defer></script>
{% render_block "js" %}
</body>
</html>

portfolio/templates/detection.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
	<div class="container-fluid pg-banner">	
		<div class="container">	
			<div class="col-xs-12 banner-content">
				<h3 class="animate wow fadeInUp">Detection</h3>
			</div>
		</div>
	</div>
	<div class="container-fluid welcome-fluid ">
		<div class="container">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="col-sm-5 col-xs-12 contact-form">
					<form method="post">
						<div class="col-xs-12">
							<div id="image-preview">
								<label for="image-upload" id="image-label">Choose File</label>
								<input type="file" name="image" id="image-upload" />
							</div>
						</div>
						<div class="col-xs-12">
							<button type="submit" class="btn">Submit</button>
						</div>
					</form>
				</div>
				<div class="col-sm-7 col-xs-12 detected-txt ">
					<div class="col-xs-12">
						<h4>Here are a few human pictures</h4>
						<p>Prediction after submission of image.</p>
					</div>
				</div>
				
			</div>
		</div>
	</div>
	
{% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static 'js/jquery.uploadPreview.js' %}"></script>
	<script type="text/javascript">
		$(document).ready(function() {
		  $.uploadPreview({
			input_field: "#image-upload",   // Default: .image-upload
			preview_box: "#image-preview",  // Default: .image-preview
			label_field: "#image-label",    // Default: .image-label
			label_default: "Choose File",   // Default: Choose File
			label_selected: "Change File",  // Default: Change File
			no_label: false                 // Default: false
		  });
		});
	</script>
{% endblock %}

portfolio/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <section id="home">
	<div class="container-fluid welcome-fluid hm-fluid-pad">
		<div class="container">
			  <div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12 hm-content">
					<div class="col-xs-12 hm-left-div animate wow fadeInLeft" style="animation-delay:1s;">
						<div class="col-xs-12 paddingZ">
							<img class="img-responsive m-auto" src="{% static 'img/AboutImg.jpg' %}">
						</div>
					</div>
					<div class="col-sm-8 col-xs-12 hm-right-div">
						<ul class="hm-list">
                            {% for skill in skills %}
							    <li class="animate wow flipInX">{{ skill.title }}</li>
                            {% endfor %}
						</ul>
					</div>
					<div class="col-xs-12 hm-contact">
						<div class="col-sm-6 col-xs-12">
							<h5 class="animate wow fadeInUp" style="animation-delay:1.4s;" >Visit my profile on:</h5>
							<p class="links-profile paddingZ animate wow fadeInUp" style="animation-delay:1.6s;">
								<a href="https://github.com/rohit-patel" target="_blank">Github</a>
								<a href="https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=2948023" target="_blank">SSRN</a>
								<a href="https://www.theinternetofthings.eu/rohit-patel" target="_blank"> IoT Council member</a>
							</p>
						</div>
						<div class="col-sm-6 col-xs-12">
							<p class="animate wow fadeInUp" style="animation-delay:1.2s;">For questions regarding <strong>AI</strong> in business Email me at <a href="mailto:"><strong>contact@rohit-patel.com</strong></a></p>
						</div>
					</div>
				</div>
			</div>
			</div>
     </div>
</section>


{% endblock %}

portfolio/templates/latex_beamer.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid pg-banner">
		<div class="container">
			<div class="col-xs-12 banner-content">
				<h3 class="animate wow fadeInUp">LaTeX Beamer Themes</h3>
			</div>
		</div>
	</div>
	<div class="container-fluid welcome-fluid">
		<div class="container">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="col-xs-12 theme-div" style="">
					<p class="animate wow fadeInUp">When I was set to present my work while at Kellogg, I decided to tinker with the beamer styles. Here are the results.</p>
					<h5 class="animate wow fadeInUp">Note: More specific themes can be found here for <a href="#">Northwestern</a> and <a href="#">Kellogg</a> students.</h5>
					<h4 class="animate wow flipInX">Changelog and Usage Instructions</h4>
					<ul>
						<li class="animate wow">First, here is the pdf output: <a href="https://www.dropbox.com/s/paapp9sev9rdl92/Econ1.pdf?dl=1" target="_blank">Econ1.pdf</a></li>
						<li class="animate wow">You will need to place the file <a href="https://www.dropbox.com/s/odju4hqhn2v7fa9/beamerthemeEcon1.sty?dl=1" target="_blank"> beamerthemeEcon1.sty</a>, along with any logo files, in the folder where your tex file is located.</li>
						<li class="animate wow">The Theme is quite customizable. A logo can be added to the title page by adding the following line to the preamble before the theme is invoked
							<br><br><code>\def\Logo{logofilename.extension}</code><br><br>Where the extension can be pdf/eps/png/jpg etc...
						</li>
						<li class="animate wow">The default color can be changed, by passing the structure argument as for the inbuilt beamer themes<br>
							<br><code>\usecolortheme[RGB={47,104,150}]{structure}</code>
						</li>
						<li class="animate wow">The text in any of the boxes in the footer can be defined by issuing the commands:<br>
							<br><code>\def\UpperLeftBoxText{Upper Left Box Text}</code><br>
							<br><code>\def\UpperRightBoxText{Upper Right Box Text}</code><br>
							<br><code>\def\ShadedLeftBoxText{Shaded Left Box Text}</code><br>
							<br><code>\def\ShadedRightBoxText{Shaded Right Box Text}</code>
						</li>
						<li class="animate wow">
							The default behavior is to not list the institute(s) of the author(s) on the title page when a logo is specified and to list it (as is normally the case) when there is no logo added. However, sometime you may want to have both. The following command can be added to the preamble to force the institute name on the title page even in the presence of the logo.
							<br><br><code>\def\ForceInstitute{}</code><br><br>
							This command does nothing when there is no logo present.
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

portfolio/templates/latex_beamer_kellogg.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid pg-banner">
		<div class="container">
			<div class="col-xs-12 banner-content">
				<h3 class="animate wow fadeInUp">LaTex Beamer Presentation Theme for Kellogg</h3>
			</div>
		</div>
	</div>
	<div class="container-fluid welcome-fluid">
		<div class="container">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="col-xs-12 theme-div">
					<p class="animate wow fadeInUp">Here is a theme for Latex presentations. It is made to look like one of the powerpoint presentation templates provided by Kellogg. A more general theme can be found here.</p>
					<h4 class="animate wow fadeInUp">Changelog and Usage Instructions</h4>
					<ul>
						<li class="animate wow">First, here is the pdf output: <a href="https://www.dropbox.com/s/s2wa2g8348tllny/Kellogg_template.pdf?dl=1" target="_blank">Kellogg_template.pdf</a></li>
						<li class="animate wow">The proof environment will not provide you with a standard block and "Proof.". Instead, it will simply say "Sketch of Proof." and skip to the next line.
							If you need the old proof environment, use oldproof. If you need simply "Proof." instead of "Sketch of Proof.",
							with the simple style, use fullproof.  The reason for this change is that I have never seen anyone in Economics present a full
							proof on a presentation, and the equations are often too unwieldy to look pretty in a block anyway.
						</li>
						<li class="animate wow">The default color is purple for the Kellogg theme. It can be changed however, by passing the structure argument as for the inbuilt beamer themes.
						</li>
						<li class="animate wow">You will need to place the files beamerthemeKellogg.sty, NUidentity_white.pdf, and Kellogg_logo_white.pdf in the folder where your tex file is located.
						</li >
						<li class="animate wow">
							The use of Kellogg logo and identity files is governed by university guidelines that can be found here and here.
						</li>
						<li class="animate wow">
							Invoke the theme by using the command \usetheme{Kellogg} in the preamble
						</li>
						<li class="animate wow">
							The second line after the frametitle can be rid of by adding to the preamble<br><code>\def\NoTitleUnderline{}</code>
						</li>
						<li class="animate wow">
							The tex file that generated the output above: Kellogg_template.tex
						</li>
						<li class="animate wow">
							Members of NU/Kellogg community can use the files freely. However, I request that you link directly to this page when distributing these files so that the user does not accidentally violate the NU/Kellogg usage guidelines.
						</li>
					</ul>
					<p class="animate wow fadeInUp">If you have a theme, or have edited this theme to look different, send me an email with the sty file and a link to your website and I'll add it here.</p>
					<ol>
						<li class="animate wow">Output of a modified beamerthemeKelloggBKevin.sty by Kevin Bryan.</li>
					</ol>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

portfolio/templates/latex_beamer_northwestern.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid pg-banner">
		<div class="container">
			<div class="col-xs-12 banner-content">
				<h3 class="animate wow fadeInUp">LaTeX Beamer Presentation Theme for Northwestern</h3>
			</div>
		</div>
	</div>
	<div class="container-fluid welcome-fluid">
		<div class="container">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="col-xs-12 theme-div">
					<p class="animate wow fadeInUp">Here is a Northwestern theme for LaTeX presentations. A more general theme can be found here.</p>
					<h4 class="animate wow fadeInUp">Changelog and Usage Instructions</h4>
					<ul>
						<li class="animate wow">First, here is the pdf output: <a href="https://www.dropbox.com/s/x46ecmncjsv1y5r/NU_template.pdf?dl=1" target="_blank">NU_template.pdf</a></li>
						<li class="animate wow">The proof environment will not provide you with a standard block and "Proof.". Instead, it will simply say "Sketch of Proof."
							and skip to the next line. If you need the old proof environment, use oldproof. If you need simply "Proof." instead of "Sketch of Proof.
							", with the simple style, use fullproof.  The reason for this change is that I have never seen anyone in Economics present a full proof on
							a presentation, and the equations are often too unwieldy to look pretty in a block anyway.
						</li>
						<li class="animate wow">The default color is purple for the NU theme. It can be changed however, by passing the structure argument as for the inbuilt beamer themes.
						</li>
						<li class="animate wow">You will need to place the files <br>
							<a href="">BeamerThemeNorthwestern.sty</a><br>
							<a href="#"> NUidentity_white.pdf</a> and<br>
							 <a href="#">NU_logo_purple.pdf</a><br>
							in the folder where your tex file is located.
						</li>
						<li class="animate wow">
							The use of Kellogg logo and identity files is governed by university guidelines that can be found <a href="http://www.northwestern.edu/univ-relations/identity-system/guidelines.html" target="_blank">here</a>.
						</li>
						<li class="animate wow">
							Invoke the theme by using the command <code>\usetheme{Kellogg}</code> in the preamble
						</li>
						<li class="animate wow">
							The second line after the frametitle can be rid of by adding to the preamble<br><code>\def\NoTitleUnderline{}</code>
						</li>
						<li class="animate wow">
							The tex file that generated the output above: <a href="https://www.dropbox.com/s/l67no5i0qnmpzbq/NU" target="_blank">Kellogg_template.tex</a>
						</li>
						<li class="animate wow">
							Members of NU/Kellogg community can use the files freely. However, I request that you link directly to this page when distributing these files so that the user does not accidentally violate the NU/Kellogg usage guidelines.
						</li>
					</ul>

				</div>
			</div>
		</div>
	</div>
{% endblock %}

portfolio/templates/meet_ai.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid pg-banner">
        <div class="container">
            <div class="col-xs-12 banner-content">
                <h3 class="animate wow fadeInUp">Meet the AI</h3>
            </div>
        </div>
    </div>
    <div class="container-fluid welcome-fluid">
        <div class="container">
            <div class="row theme-cat-row">
                {% for project in ai_projects %}
                <div class="col-sm-4 col-xs-12 animate wow zoomIn" style="animation-delay:0.2s">
                    <a href="#">
                        <div class="col-xs-12 theme-cat">
                            <h4>{{ project.title }}</h4>
                            <div class="theme-view-more">
                                <p>View More</p>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

portfolio/templates/menu.html
<div class="navbar custom-navbar navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon icon-bar"></span>
                <span class="icon icon-bar"></span>
                <span class="icon icon-bar"></span>
            </button>
            <a href="{% url 'main:homepage' %}" class="navbar-brand">Rohit Patel</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="{% if request.resolver_match.url_name == "homepage" %}active{% endif %}" id="home"><a class="smoothScroll" href="{% url 'main:homepage' %}">Home</a></li>
                <li id="ai" class="{% if request.resolver_match.url_name == "meet_ai" %}active{% endif %}"><a class="smoothScroll" href="{% url 'main:meet_ai' %}">Meet The AI</a></li>
                <li id="resume" class="{% if request.resolver_match.url_name == "resume" %}active{% endif %}"><a class="smoothScroll" href="{% url 'main:resume' %}">Resume</a></li>
                <li id="research" class="{% if request.resolver_match.url_name == "research" %}active{% endif %}"><a class="smoothScroll" href="{% url 'main:research' %}">Research</a></li>
                <li id="theme" class="dropdown {% if request.resolver_match.url_name == "latex_beamer_theme" %}active{% endif %}"><a href="{% url 'main:latex_beamer_theme' %}">Latex Beamer Themes</a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'main:latex_beamer_theme' %}">LaTeX Beamer Themes</a></li>
                        <li><a href="{% url 'main:latex_beamer_kellogg' %}">LaTex Beamer Presentation Theme for Kellogg</a></li>
                        <li><a href="{% url 'main:latex_beamer_northwestern' %}">LaTeX Beamer Presentation Theme for Northwestern</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>

portfolio/templates/research.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid pg-banner">
		<div class="container">
			<div class="col-xs-12 banner-content">
				<h3 class="animate wow fadeInUp">Research</h3>
			</div>
		</div>
	</div>
	<div class="container-fluid welcome-fluid">
		<div class="container">
			<div class="col-md-12 col-sm-12 col-xs-12 research-main">
				<!--  <h3 class="heading-section animate wow fadeInUp" >Research</h3> -->
                {% for research in researches %}
                    <div class="col-xs-12 research-div animate wow">
                        <a href="#">{{ research.title }}</a>, <em>with {{ research.author }}</em>
                        <p>{{ research.description }}</p>
                    </div>
                {% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

portfolio/templates/resume.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid pg-banner">
        <div class="container">
            <div class="col-xs-12 banner-content">
                <h3 class="animate wow fadeInUp">Résumé</h3>
            </div>
        </div>
    </div>
    <div class="container-fluid welcome-fluid ">
        <div class="container">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="col-sm-6 col-xs-12 theme-div ">
                    <h4 class="animate wow flipInX">Please submit <strong>Contact Form</strong> OR contact on
                        <br><strong>resume@rohit-patel.com</strong> for a copy.</h4>
                </div>
                <div class="col-sm-6 col-xs-12 contact-form">
                    <h3>Contact Me</h3>
                    <form method="post">
                        {% csrf_token %}
                        <input class="form-control" name="name" type="text" placeholder="Enter Name" required/>
                        <input class="form-control" name="email" type="email" placeholder="Enter Email" required/>
                        <input class="form-control" name="number" type="number" placeholder="Enter Contact Number" required/>
                        <textarea class="form-control" name="message" type="number" placeholder="Leave A Message..."
                                  required></textarea>
                        <button type="submit" class="btn">Submit</button>
                    </form>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

portfolio/templates/single_page.html
{% extends "base.html" %}
{% load cms_tags %}

{% block content %}
    {% placeholder foo_content %}
{% endblock %}